[package]
name = "play-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.19"
reqwest = { version = "0.11.8", features = ["blocking"] }
threadpool = "1.8.1"
tokio = { version = "1", features = ["full"] }
