[package]
name = "rust-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.2.0"
error-chain = "0.12.4"
reqwest = "0.11.8"
tokio = { version = "1", features = ["full"] }
indicatif = "0.16.2"
futures-util = "0.3.19"
